### PR TITLE
Ran ember-cli-update to 3.5.1

### PR DESCRIPTION
**Pull request by cah-danmonroe**

### CODE REVIEW

**Comment by locks** [comment]
I believe that the original idea was to keep the tutorials updated to the latest LTS version, has this changed?

**Comment by rtablada** [comment]
I'm not sure the value of ember-cli-update on an empty project since this is just a blank slate, IMO it makes more sense to just have `ember new` with a fresh slate?

**Comment by cah-danmonroe** [comment]
Ryan, I asked the same question in Discord before I did it.  Doesn't matter since everything will be overwritten by your stuff..  I should just close this PR.

**Comment by cah-danmonroe** [comment]
Ryan's update already has version as 3.5.1

**Pull request closed without merging**
